# Generated by Django 6.0.3 on 2026-03-31 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SysUser',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_number', models.CharField(max_length=20, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('full_name', models.CharField(max_length=100, null=True)),
                ('email', models.CharField(max_length=150, null=True)),
                ('department', models.CharField(max_length=100, null=True)),
                ('role', models.CharField(default='USER', max_length=50)),
                ('is_active', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'SYS_USERS',
            },
        ),
    ]
