# Generated by Django 6.0.3 on 2026-05-01 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SysModule',
            fields=[
                ('module_id', models.AutoField(primary_key=True, serialize=False)),
                ('module_name', models.CharField(max_length=100)),
                ('parent_module', models.ForeignKey(blank=True, db_column='PARENT_MODULE_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submodules', to='accounts.sysmodule')),
            ],
            options={
                'db_table': 'SYS_MODULE',
            },
        ),
        migrations.CreateModel(
            name='SysComponent',
            fields=[
                ('component_id', models.AutoField(primary_key=True, serialize=False)),
                ('component_name', models.CharField(max_length=100)),
                ('url_path', models.CharField(max_length=200, null=True)),
                ('module', models.ForeignKey(db_column='MODULE_ID', on_delete=django.db.models.deletion.CASCADE, related_name='components', to='accounts.sysmodule')),
            ],
            options={
                'db_table': 'SYS_COMPONENT',
            },
        ),
    ]
